USE injupen_db;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS tipos_propiedad (
  ID_TIPO_PROPIEDAD INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(120) NOT NULL,
  SLUG VARCHAR(140) NOT NULL,
  DESCRIPCION TEXT NULL,
  ESTADO TINYINT(1) NOT NULL DEFAULT 1,
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_TIPO_PROPIEDAD),
  UNIQUE KEY UK_TIPOS_PROPIEDAD_NOMBRE (NOMBRE),
  UNIQUE KEY UK_TIPOS_PROPIEDAD_SLUG (SLUG)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS zonas (
  ID_ZONA INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(150) NOT NULL,
  CIUDAD VARCHAR(150) NOT NULL,
  SLUG VARCHAR(180) NOT NULL,
  DESCRIPCION TEXT NULL,
  ESTADO TINYINT(1) NOT NULL DEFAULT 1,
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_ZONA),
  UNIQUE KEY UK_ZONAS_SLUG (SLUG),
  KEY IDX_ZONAS_CIUDAD (CIUDAD),
  KEY IDX_ZONAS_ESTADO (ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agentes (
  ID_AGENTE INT NOT NULL AUTO_INCREMENT,
  ID_USUARIO INT NULL,
  NOMBRE VARCHAR(180) NOT NULL,
  CARGO VARCHAR(150) NOT NULL,
  TELEFONO VARCHAR(40) NOT NULL,
  CORREO VARCHAR(180) NOT NULL,
  FOTO_URL VARCHAR(500) NULL,
  ESPECIALIDAD VARCHAR(180) NULL,
  ESTADO ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_AGENTE),
  UNIQUE KEY UK_AGENTES_CORREO (CORREO),
  KEY IDX_AGENTES_ESTADO (ESTADO),
  KEY IDX_AGENTES_USUARIO (ID_USUARIO),
  CONSTRAINT FK_AGENTES_USUARIO
    FOREIGN KEY (ID_USUARIO) REFERENCES gestion_usuarios (CODIGO)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS propiedades (
  ID_PROPIEDAD INT NOT NULL AUTO_INCREMENT,
  ID_TIPO_PROPIEDAD INT NOT NULL,
  ID_ZONA INT NOT NULL,
  ID_AGENTE INT NOT NULL,
  TITULO VARCHAR(220) NOT NULL,
  SLUG VARCHAR(260) NOT NULL,
  OPERACION ENUM('Venta', 'Renta') NOT NULL,
  PRECIO DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  HABITACIONES INT NOT NULL DEFAULT 0,
  BANOS DECIMAL(4,1) NOT NULL DEFAULT 0.0,
  ESTACIONAMIENTOS INT NOT NULL DEFAULT 0,
  AREA_M2 DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  DIRECCION VARCHAR(255) NOT NULL,
  DESCRIPCION TEXT NOT NULL,
  IMAGEN_PORTADA LONGTEXT NULL,
  DESTACADA TINYINT(1) NOT NULL DEFAULT 0,
  ACTIVA TINYINT(1) NOT NULL DEFAULT 1,
  ESTADO_COMERCIAL ENUM('Disponible', 'Vendida', 'Rentada', 'Inactiva') NOT NULL DEFAULT 'Disponible',
  ESTADO_PUBLICACION ENUM('Borrador', 'Pendiente de pago', 'Publicada', 'Vencida', 'Pausada') NOT NULL DEFAULT 'Borrador',
  FECHA_PUBLICACION TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_PROPIEDAD),
  UNIQUE KEY UK_PROPIEDADES_SLUG (SLUG),
  KEY IDX_PROPIEDADES_TIPO (ID_TIPO_PROPIEDAD),
  KEY IDX_PROPIEDADES_ZONA (ID_ZONA),
  KEY IDX_PROPIEDADES_AGENTE (ID_AGENTE),
  KEY IDX_PROPIEDADES_OPERACION (OPERACION),
  KEY IDX_PROPIEDADES_DESTACADA (DESTACADA),
  KEY IDX_PROPIEDADES_ACTIVA (ACTIVA),
  KEY IDX_PROPIEDADES_ESTADO_COMERCIAL (ESTADO_COMERCIAL),
  KEY IDX_PROPIEDADES_ESTADO_PUBLICACION (ESTADO_PUBLICACION),
  CONSTRAINT FK_PROPIEDADES_TIPO
    FOREIGN KEY (ID_TIPO_PROPIEDAD) REFERENCES tipos_propiedad (ID_TIPO_PROPIEDAD)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT FK_PROPIEDADES_ZONA
    FOREIGN KEY (ID_ZONA) REFERENCES zonas (ID_ZONA)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT FK_PROPIEDADES_AGENTE
    FOREIGN KEY (ID_AGENTE) REFERENCES agentes (ID_AGENTE)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS propiedad_imagenes (
  ID_IMAGEN INT NOT NULL AUTO_INCREMENT,
  ID_PROPIEDAD INT NOT NULL,
  URL_IMAGEN LONGTEXT NOT NULL,
  TEXTO_ALTERNATIVO VARCHAR(255) NULL,
  ORDEN_VISUAL INT NOT NULL DEFAULT 1,
  ES_PORTADA TINYINT(1) NOT NULL DEFAULT 0,
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_IMAGEN),
  KEY IDX_IMAGENES_PROPIEDAD (ID_PROPIEDAD),
  KEY IDX_IMAGENES_ORDEN (ID_PROPIEDAD, ORDEN_VISUAL),
  CONSTRAINT FK_IMAGENES_PROPIEDAD
    FOREIGN KEY (ID_PROPIEDAD) REFERENCES propiedades (ID_PROPIEDAD)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE propiedades
  MODIFY COLUMN IMAGEN_PORTADA LONGTEXT NULL;

SET @col_estado_comercial := (
  SELECT COUNT(*)
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'propiedades'
    AND COLUMN_NAME = 'ESTADO_COMERCIAL'
);
SET @sql_estado_comercial := IF(
  @col_estado_comercial = 0,
  "ALTER TABLE propiedades ADD COLUMN ESTADO_COMERCIAL ENUM('Disponible', 'Vendida', 'Rentada', 'Inactiva') NOT NULL DEFAULT 'Disponible' AFTER ACTIVA",
  'SELECT 1'
);
PREPARE stmt_estado_comercial FROM @sql_estado_comercial;
EXECUTE stmt_estado_comercial;
DEALLOCATE PREPARE stmt_estado_comercial;

SET @col_estado_publicacion := (
  SELECT COUNT(*)
  FROM information_schema.COLUMNS
  WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'propiedades'
    AND COLUMN_NAME = 'ESTADO_PUBLICACION'
);
SET @sql_estado_publicacion := IF(
  @col_estado_publicacion = 0,
  "ALTER TABLE propiedades ADD COLUMN ESTADO_PUBLICACION ENUM('Borrador', 'Pendiente de pago', 'Publicada', 'Vencida', 'Pausada') NOT NULL DEFAULT 'Borrador' AFTER ESTADO_COMERCIAL",
  'SELECT 1'
);
PREPARE stmt_estado_publicacion FROM @sql_estado_publicacion;
EXECUTE stmt_estado_publicacion;
DEALLOCATE PREPARE stmt_estado_publicacion;

ALTER TABLE propiedad_imagenes
  MODIFY COLUMN URL_IMAGEN LONGTEXT NOT NULL;

UPDATE propiedades
SET ESTADO_COMERCIAL = CASE
  WHEN ACTIVA = 0 THEN 'Inactiva'
  ELSE 'Disponible'
END
WHERE ESTADO_COMERCIAL IS NULL
   OR ESTADO_COMERCIAL = '';

UPDATE propiedades
SET ESTADO_PUBLICACION = CASE
  WHEN ACTIVA = 1 THEN 'Publicada'
  ELSE 'Borrador'
END
WHERE ESTADO_PUBLICACION IS NULL
   OR ESTADO_PUBLICACION = '';

CREATE TABLE IF NOT EXISTS solicitudes_contacto (
  ID_SOLICITUD INT NOT NULL AUTO_INCREMENT,
  ID_PROPIEDAD INT NULL,
  NOMBRE VARCHAR(180) NOT NULL,
  CORREO VARCHAR(180) NOT NULL,
  TELEFONO VARCHAR(40) NOT NULL,
  MENSAJE TEXT NOT NULL,
  ESTADO ENUM('Nuevo', 'En seguimiento', 'Cerrado') NOT NULL DEFAULT 'Nuevo',
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_SOLICITUD),
  KEY IDX_SOLICITUDES_PROPIEDAD (ID_PROPIEDAD),
  KEY IDX_SOLICITUDES_ESTADO (ESTADO),
  KEY IDX_SOLICITUDES_FECHA (FECHA_CREACION),
  CONSTRAINT FK_SOLICITUDES_PROPIEDAD
    FOREIGN KEY (ID_PROPIEDAD) REFERENCES propiedades (ID_PROPIEDAD)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ventas_propiedades (
  ID_VENTA INT NOT NULL AUTO_INCREMENT,
  ID_PROPIEDAD INT NOT NULL,
  ID_AGENTE INT NOT NULL,
  NOMBRE_CLIENTE VARCHAR(180) NOT NULL,
  IDENTIDAD_CLIENTE VARCHAR(80) NULL,
  TELEFONO_CLIENTE VARCHAR(40) NULL,
  CORREO_CLIENTE VARCHAR(180) NULL,
  PRECIO_PUBLICADO DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  PRECIO_CIERRE DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  TIPO_NEGOCIO ENUM('Venta', 'Renta') NOT NULL,
  PORCENTAJE_COMISION DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  MONTO_COMISION DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  FECHA_CIERRE DATE NOT NULL,
  ESTADO_VENTA ENUM('Cerrada', 'Anulada') NOT NULL DEFAULT 'Cerrada',
  OBSERVACIONES TEXT NULL,
  USUARIO_CREACION INT NULL,
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_VENTA),
  KEY IDX_VENTAS_PROPIEDAD (ID_PROPIEDAD),
  KEY IDX_VENTAS_AGENTE (ID_AGENTE),
  KEY IDX_VENTAS_FECHA_CIERRE (FECHA_CIERRE),
  KEY IDX_VENTAS_ESTADO (ESTADO_VENTA),
  CONSTRAINT FK_VENTAS_PROPIEDAD
    FOREIGN KEY (ID_PROPIEDAD) REFERENCES propiedades (ID_PROPIEDAD)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT FK_VENTAS_AGENTE
    FOREIGN KEY (ID_AGENTE) REFERENCES agentes (ID_AGENTE)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT FK_VENTAS_USUARIO_CREACION
    FOREIGN KEY (USUARIO_CREACION) REFERENCES gestion_usuarios (CODIGO)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS comisiones (
  ID_COMISION INT NOT NULL AUTO_INCREMENT,
  ID_VENTA INT NOT NULL,
  ID_AGENTE INT NOT NULL,
  PORCENTAJE_COMISION DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  MONTO_COMISION DECIMAL(14,2) NOT NULL DEFAULT 0.00,
  ESTADO_COMISION ENUM('Pendiente', 'Pagada', 'Parcial') NOT NULL DEFAULT 'Pendiente',
  FECHA_GENERACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_PAGO DATE NULL,
  OBSERVACIONES_PAGO TEXT NULL,
  PRIMARY KEY (ID_COMISION),
  UNIQUE KEY UK_COMISIONES_VENTA (ID_VENTA),
  KEY IDX_COMISIONES_AGENTE (ID_AGENTE),
  KEY IDX_COMISIONES_ESTADO (ESTADO_COMISION),
  CONSTRAINT FK_COMISIONES_VENTA
    FOREIGN KEY (ID_VENTA) REFERENCES ventas_propiedades (ID_VENTA)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_COMISIONES_AGENTE
    FOREIGN KEY (ID_AGENTE) REFERENCES agentes (ID_AGENTE)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS planes_publicacion (
  ID_PLAN INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(150) NOT NULL,
  SLUG VARCHAR(180) NOT NULL,
  DESCRIPCION TEXT NULL,
  PRECIO DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  DURACION_DIAS INT NOT NULL DEFAULT 30,
  LIMITE_IMAGENES INT NOT NULL DEFAULT 10,
  ADMITE_DESTACADA TINYINT(1) NOT NULL DEFAULT 0,
  NIVEL_PRIORIDAD INT NOT NULL DEFAULT 1,
  ESTADO TINYINT(1) NOT NULL DEFAULT 1,
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_PLAN),
  UNIQUE KEY UK_PLANES_PUBLICACION_NOMBRE (NOMBRE),
  UNIQUE KEY UK_PLANES_PUBLICACION_SLUG (SLUG),
  KEY IDX_PLANES_PUBLICACION_ESTADO (ESTADO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS suscripciones_publicacion (
  ID_SUSCRIPCION INT NOT NULL AUTO_INCREMENT,
  ID_PROPIEDAD INT NOT NULL,
  ID_PLAN INT NOT NULL,
  ID_AGENTE INT NULL,
  PRECIO_PLAN DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  PRECIO_FINAL DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  FECHA_INICIO DATE NOT NULL,
  FECHA_FIN DATE NOT NULL,
  ESTADO_SUSCRIPCION ENUM('Pendiente de pago', 'Activa', 'Vencida', 'Cancelada') NOT NULL DEFAULT 'Pendiente de pago',
  AUTO_RENOVAR TINYINT(1) NOT NULL DEFAULT 0,
  OBSERVACIONES TEXT NULL,
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_SUSCRIPCION),
  KEY IDX_SUSCRIPCIONES_PROPIEDAD (ID_PROPIEDAD),
  KEY IDX_SUSCRIPCIONES_PLAN (ID_PLAN),
  KEY IDX_SUSCRIPCIONES_AGENTE (ID_AGENTE),
  KEY IDX_SUSCRIPCIONES_ESTADO (ESTADO_SUSCRIPCION),
  KEY IDX_SUSCRIPCIONES_FECHAS (FECHA_INICIO, FECHA_FIN),
  CONSTRAINT FK_SUSCRIPCIONES_PROPIEDAD
    FOREIGN KEY (ID_PROPIEDAD) REFERENCES propiedades (ID_PROPIEDAD)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_SUSCRIPCIONES_PLAN
    FOREIGN KEY (ID_PLAN) REFERENCES planes_publicacion (ID_PLAN)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT FK_SUSCRIPCIONES_AGENTE
    FOREIGN KEY (ID_AGENTE) REFERENCES agentes (ID_AGENTE)
    ON DELETE SET NULL
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pagos_suscripcion (
  ID_PAGO INT NOT NULL AUTO_INCREMENT,
  ID_SUSCRIPCION INT NOT NULL,
  MONTO DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  METODO_PAGO ENUM('Transferencia', 'Efectivo', 'Tarjeta', 'Deposito', 'Otro') NOT NULL DEFAULT 'Transferencia',
  REFERENCIA_PAGO VARCHAR(180) NULL,
  ESTADO_PAGO ENUM('Pendiente', 'Pagado', 'Rechazado') NOT NULL DEFAULT 'Pendiente',
  FECHA_PAGO DATE NULL,
  OBSERVACIONES TEXT NULL,
  FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_PAGO),
  KEY IDX_PAGOS_SUSCRIPCION (ID_SUSCRIPCION),
  KEY IDX_PAGOS_ESTADO (ESTADO_PAGO),
  CONSTRAINT FK_PAGOS_SUSCRIPCION
    FOREIGN KEY (ID_SUSCRIPCION) REFERENCES suscripciones_publicacion (ID_SUSCRIPCION)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE gestion_usuarios
ADD COLUMN IF NOT EXISTS REQUIERE_ACEPTACION_TERMINOS TINYINT(1) NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS aceptaciones_terminos (
  ID_ACEPTACION INT NOT NULL AUTO_INCREMENT,
  CODIGO_USUARIO INT NOT NULL,
  VERSION_TERMINOS VARCHAR(20) NOT NULL,
  TITULO_TERMINOS VARCHAR(255) NOT NULL,
  TEXTO_ACEPTADO LONGTEXT NOT NULL,
  TIPO_ACEPTACION VARCHAR(60) NOT NULL DEFAULT 'PRIMER_INGRESO',
  FECHA_ACEPTACION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_ACEPTACION),
  KEY IDX_ACEPTACIONES_USUARIO (CODIGO_USUARIO),
  KEY IDX_ACEPTACIONES_VERSION (VERSION_TERMINOS),
  CONSTRAINT FK_ACEPTACIONES_USUARIO
    FOREIGN KEY (CODIGO_USUARIO) REFERENCES gestion_usuarios (CODIGO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO tipos_propiedad (NOMBRE, SLUG, DESCRIPCION) VALUES
('Casa', 'casa', 'Residencias familiares listas para habitar.'),
('Apartamento', 'apartamento', 'Espacios urbanos modernos y funcionales.'),
('Terreno', 'terreno', 'Lotes con alto potencial de desarrollo.');

INSERT IGNORE INTO planes_publicacion (NOMBRE, SLUG, DESCRIPCION, PRECIO, DURACION_DIAS, LIMITE_IMAGENES, ADMITE_DESTACADA, NIVEL_PRIORIDAD, ESTADO) VALUES
('Basico', 'basico', 'Plan inicial para publicar una propiedad con presencia esencial en el portal.', 35.00, 30, 8, 0, 1, 1),
('Plus', 'plus', 'Mayor visibilidad, mas imagenes y opcion destacada para propiedades con rotacion comercial.', 65.00, 30, 18, 1, 2, 1),
('Premium', 'premium', 'Exposicion prioritaria con mas tiempo de publicacion y configuracion destacada.', 110.00, 60, 30, 1, 3, 1);

INSERT INTO suscripciones_publicacion (
  ID_PROPIEDAD, ID_PLAN, ID_AGENTE, PRECIO_PLAN, PRECIO_FINAL, FECHA_INICIO, FECHA_FIN,
  ESTADO_SUSCRIPCION, AUTO_RENOVAR, OBSERVACIONES
)
SELECT
  p.ID_PROPIEDAD,
  pl.ID_PLAN,
  p.ID_AGENTE,
  pl.PRECIO,
  pl.PRECIO,
  CURDATE(),
  DATE_ADD(CURDATE(), INTERVAL pl.DURACION_DIAS - 1 DAY),
  'Activa',
  0,
  'Suscripcion inicial generada para conservar la publicacion existente.'
FROM propiedades p
INNER JOIN planes_publicacion pl
  ON pl.SLUG = 'plus'
LEFT JOIN suscripciones_publicacion s
  ON s.ID_PROPIEDAD = p.ID_PROPIEDAD
WHERE p.ACTIVA = 1
  AND p.ESTADO_COMERCIAL = 'Disponible'
  AND s.ID_SUSCRIPCION IS NULL;

INSERT INTO pagos_suscripcion (
  ID_SUSCRIPCION, MONTO, METODO_PAGO, REFERENCIA_PAGO, ESTADO_PAGO, FECHA_PAGO, OBSERVACIONES
)
SELECT
  s.ID_SUSCRIPCION,
  s.PRECIO_FINAL,
  'Transferencia',
  CONCAT('MIG-', s.ID_SUSCRIPCION),
  'Pagado',
  CURDATE(),
  'Pago inicial generado para la migracion de propiedades publicadas.'
FROM suscripciones_publicacion s
LEFT JOIN pagos_suscripcion ps
  ON ps.ID_SUSCRIPCION = s.ID_SUSCRIPCION
WHERE s.OBSERVACIONES = 'Suscripcion inicial generada para conservar la publicacion existente.'
  AND ps.ID_PAGO IS NULL;

INSERT IGNORE INTO zonas (NOMBRE, CIUDAD, SLUG, DESCRIPCION) VALUES
('Lomas del Guijarro', 'Tegucigalpa', 'lomas-del-guijarro', 'Zona residencial premium con acceso rapido.'),
('Palmira', 'Tegucigalpa', 'palmira', 'Area centrica ideal para inversion y oficinas.'),
('San Ignacio', 'Tegucigalpa', 'san-ignacio', 'Entorno tranquilo con excelente conectividad.'),
('El Trapiche', 'Tegucigalpa', 'el-trapiche', 'Area en crecimiento para vivienda y comercio.');

INSERT IGNORE INTO agentes (ID_USUARIO, NOMBRE, CARGO, TELEFONO, CORREO, FOTO_URL, ESPECIALIDAD, ESTADO) VALUES
(NULL, 'Daniela Flores', 'Asesora senior', '+504 9944-1100', 'daniela@jmlainmobiliaria.hn', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80', 'Residencial premium', 'Activo'),
(NULL, 'Miguel Castillo', 'Consultor de inversion', '+504 9888-2200', 'miguel@jmlainmobiliaria.hn', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80', 'Propiedades para renta y retorno', 'Activo');

INSERT IGNORE INTO propiedades (
  ID_TIPO_PROPIEDAD,
  ID_ZONA,
  ID_AGENTE,
  TITULO,
  SLUG,
  OPERACION,
  PRECIO,
  HABITACIONES,
  BANOS,
  ESTACIONAMIENTOS,
  AREA_M2,
  DIRECCION,
  DESCRIPCION,
  IMAGEN_PORTADA,
  DESTACADA,
  ACTIVA
) VALUES
(1, 1, 1, 'Casa con jardin en Lomas del Guijarro', 'casa-con-jardin-lomas-del-guijarro', 'Venta', 325000.00, 4, 3.5, 2, 320.00, 'Circuito principal, Lomas del Guijarro', 'Casa de dos niveles con acabados contemporaneos, jardin privado y terraza social. Ideal para familias que buscan seguridad, iluminacion natural y cercania a colegios y comercios.', 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80', 1, 1),
(2, 2, 2, 'Apartamento ejecutivo en Palmira', 'apartamento-ejecutivo-en-palmira', 'Renta', 1800.00, 2, 2.0, 2, 145.00, 'Torre residencial, Palmira', 'Apartamento con lobby, balcon panoramico, cocina abierta y seguridad 24/7. Pensado para ejecutivos y parejas que quieren vivir cerca del distrito financiero.', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80', 1, 1),
(3, 4, 2, 'Terreno estrategico en El Trapiche', 'terreno-estrategico-en-el-trapiche', 'Venta', 210000.00, 0, 0.0, 0, 980.00, 'Acceso principal a El Trapiche', 'Terreno plano con excelente frente y alto potencial para vivienda o desarrollo comercial. Cuenta con acceso a servicios basicos y alta visibilidad.', 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80', 0, 1),
(1, 3, 1, 'Casa familiar en San Ignacio', 'casa-familiar-en-san-ignacio', 'Venta', 278000.00, 3, 2.5, 2, 250.00, 'Boulevard residencial, San Ignacio', 'Propiedad con amplias areas sociales, estudio independiente y patio con pergola. Actualmente inactiva para publicacion pero disponible para gestion administrativa.', 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80', 0, 0);

INSERT IGNORE INTO propiedad_imagenes (ID_PROPIEDAD, URL_IMAGEN, TEXTO_ALTERNATIVO, ORDEN_VISUAL, ES_PORTADA) VALUES
(1, 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80', 'Casa con jardin en Lomas del Guijarro', 1, 1),
(1, 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80', 'Sala principal de la propiedad', 2, 0),
(1, 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80', 'Terraza social de la propiedad', 3, 0),
(2, 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80', 'Apartamento ejecutivo en Palmira', 1, 1),
(2, 'https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80', 'Cocina del apartamento', 2, 0),
(2, 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80', 'Dormitorio del apartamento', 3, 0),
(3, 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80', 'Terreno estrategico en El Trapiche', 1, 1),
(3, 'https://images.unsplash.com/photo-1448630360428-65456885c650?auto=format&fit=crop&w=1200&q=80', 'Vista general del terreno', 2, 0),
(4, 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80', 'Casa familiar en San Ignacio', 1, 1),
(4, 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=1200&q=80', 'Jardin y fachada de la casa', 2, 0);

INSERT IGNORE INTO solicitudes_contacto (ID_PROPIEDAD, NOMBRE, CORREO, TELEFONO, MENSAJE, ESTADO) VALUES
(2, 'Ana Pineda', 'ana.pineda@email.com', '+504 9911-3322', 'Quiero agendar una visita para el apartamento en Palmira.', 'Nuevo');
