USE inmobiliaria_db;

CREATE TABLE IF NOT EXISTS configuracion_comisiones (
  ID_CONFIGURACION INT NOT NULL AUTO_INCREMENT,
  COMISION_MINIMA DECIMAL(6,2) NOT NULL DEFAULT 5.00,
  COMISION_MAXIMA DECIMAL(6,2) NOT NULL DEFAULT 15.00,
  COMISION_POR_DEFECTO DECIMAL(6,2) NOT NULL DEFAULT 5.00,
  PORCENTAJE_AGENTE_POR_DEFECTO DECIMAL(6,2) NOT NULL DEFAULT 5.00,
  FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_CONFIGURACION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO configuracion_comisiones (
  COMISION_MINIMA,
  COMISION_MAXIMA,
  COMISION_POR_DEFECTO,
  PORCENTAJE_AGENTE_POR_DEFECTO
)
SELECT 5.00, 15.00, 5.00, 5.00
WHERE NOT EXISTS (
  SELECT 1
  FROM configuracion_comisiones
);

UPDATE configuracion_comisiones
SET PORCENTAJE_AGENTE_POR_DEFECTO = LEAST(
  COMISION_MAXIMA,
  GREATEST(COMISION_MINIMA, PORCENTAJE_AGENTE_POR_DEFECTO)
);
