USE inmobiliaria_db;

ALTER TABLE comisiones
  ADD COLUMN IF NOT EXISTS PORCENTAJE_AGENTE DECIMAL(6,2) NOT NULL DEFAULT 95.00 AFTER MONTO_COMISION,
  ADD COLUMN IF NOT EXISTS MONTO_AGENTE DECIMAL(14,2) NOT NULL DEFAULT 0.00 AFTER PORCENTAJE_AGENTE,
  ADD COLUMN IF NOT EXISTS PORCENTAJE_PROPIETARIO DECIMAL(6,2) NOT NULL DEFAULT 5.00 AFTER MONTO_AGENTE,
  ADD COLUMN IF NOT EXISTS MONTO_PROPIETARIO DECIMAL(14,2) NOT NULL DEFAULT 0.00 AFTER PORCENTAJE_PROPIETARIO;

UPDATE comisiones
SET
  PORCENTAJE_PROPIETARIO = COALESCE(NULLIF(PORCENTAJE_PROPIETARIO, 0), 5.00),
  PORCENTAJE_AGENTE = 100.00 - COALESCE(NULLIF(PORCENTAJE_PROPIETARIO, 0), 5.00),
  MONTO_PROPIETARIO = ROUND(
    MONTO_COMISION * (COALESCE(NULLIF(PORCENTAJE_PROPIETARIO, 0), 5.00) / 100),
    2
  ),
  MONTO_AGENTE = ROUND(
    MONTO_COMISION - ROUND(MONTO_COMISION * (COALESCE(NULLIF(PORCENTAJE_PROPIETARIO, 0), 5.00) / 100), 2),
    2
  );
