const db = require('../db');

const DEFAULT_SETTINGS = {
  COMISION_MINIMA: 5,
  COMISION_MAXIMA: 15,
  COMISION_POR_DEFECTO: 5,
  PORCENTAJE_AGENTE_POR_DEFECTO: 5,
};

const ensureCommissionSettingsSchema = async () => {
  await db.query(`
    CREATE TABLE IF NOT EXISTS configuracion_comisiones (
      ID_CONFIGURACION INT NOT NULL AUTO_INCREMENT,
      COMISION_MINIMA DECIMAL(6,2) NOT NULL DEFAULT 5.00,
      COMISION_MAXIMA DECIMAL(6,2) NOT NULL DEFAULT 15.00,
      COMISION_POR_DEFECTO DECIMAL(6,2) NOT NULL DEFAULT 5.00,
      PORCENTAJE_AGENTE_POR_DEFECTO DECIMAL(6,2) NOT NULL DEFAULT 5.00,
      FECHA_ACTUALIZACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (ID_CONFIGURACION)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
  `);

  const [rows] = await db.query(
    'SELECT ID_CONFIGURACION FROM configuracion_comisiones ORDER BY ID_CONFIGURACION ASC LIMIT 1'
  );

  if (rows.length) {
    return;
  }

  await db.query(
    `INSERT INTO configuracion_comisiones (
      COMISION_MINIMA, COMISION_MAXIMA, COMISION_POR_DEFECTO, PORCENTAJE_AGENTE_POR_DEFECTO
    ) VALUES (?, ?, ?, ?)`,
    [
      DEFAULT_SETTINGS.COMISION_MINIMA,
      DEFAULT_SETTINGS.COMISION_MAXIMA,
      DEFAULT_SETTINGS.COMISION_POR_DEFECTO,
      DEFAULT_SETTINGS.PORCENTAJE_AGENTE_POR_DEFECTO,
    ]
  );
};

module.exports = {
  DEFAULT_SETTINGS,
  ensureCommissionSettingsSchema,
};
